#!/usr/bin/env bash

active () {
    hyprctl monitors -j | jq -Mc "map(.activeWorkspace.id)"
}

active
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	active
done
