#!/usr/bin/env bash

spaces (){
    WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
    workspace-arranger | jq --argjson windows "${WORKSPACE_WINDOWS}" -Mc 'map(.workspaces | map(tostring) | map({id: ., windows: ($windows[.]//0)}))'
}

spaces
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    spaces
done
