#!/bin/bash

spaces (){
    MONITORS=$(hyprctl monitors -j | jq 'map(.id)')
    WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
    echo $MONITORS | jq --argjson windows "${WORKSPACE_WINDOWS}" -Mc 'map([range(. * 5 + 1; (. + 1) * 5 + 1)] | map(tostring) | map({id: ., windows: ($windows[.]//0)}))'
}

spaces
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    spaces
done
