#! /bin/bash
function clamp {
    min=$1
    max=$2
    val=$3
    python -c "print(max($min, min($val, $max)))"
}

monitor=$1
direction=$2
current=$3

min_workspace=$(($monitor * 5 + 1))
max_workspace=$((($monitor + 1) * 5))

if test "$direction" = "down"
then
    target=$(clamp $min_workspace $max_workspace $(($current+1)))
    echo "jumping to $target"
    hyprctl dispatch workspace $target
elif test "$direction" = "up"
then
    target=$(clamp $min_workspace $max_workspace $(($current-1)))
    echo "jumping to $target"
    hyprctl dispatch workspace $target
fi
