#!/bin/bash

active () {
	hyprctl monitors -j | jq --raw-output ".[] | select(.id==$monitor).activeWorkspace.id"
}

monitor=$1

active
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	active
done
