is_vm = false
desktop_monitors = false
vertical_monitor = true
hass = false
hass_host = "http://192.168.0.151:8123"
nvidia = false
battery = false
auto_scaling = true
kde_connect = false
artix = false
keyboard_model = "at-translated-set-2-keyboard"
vpn_connection = false
clockin_project = false
