[bell.command]
args = ["/usr/share/sounds/freedesktop/stereo/dialog-warning.oga"]
program = "pw-play"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[scrolling]
history = 50000

[window]
dynamic_padding = true
